### ISSUE TITLE
Fail to run the demo

### ISSUE THREAD

**Issue by brness** [kinvolk/seccompagent#25]
## Description
I'm a rookie and I try to use the demo to understand the usage of seccomp agent and SECP_ACT_NOTIFY, so I follow the instruction in README, but when I apply the pod yaml into cluster, Here is the bug info
[ 1 paragraph concisely describing the bug ]
 ```Normal   Scheduled  15m   default-scheduler  Successfully assigned default/mypod to ubuntu-worker2
  Normal   Pulling    15m   kubelet            Pulling image "busybox"
  Normal   Pulled     15m   kubelet            Successfully pulled image "busybox" in 20.301974634s
  Normal   Created    15m   kubelet            Created container container1
  Warning  Failed     15m   kubelet            Error: failed to start container "container1": Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: listenerPath is not set: unknown
```

## Impact
Everything are satisfied in my k8s.
[ 1 sentence detailing the impact this bug is creating for you ]

## Environment and steps to reproduce

1. **Set-up**:  my local k8s cluster build by rancher
3. **Task**: just follow the instruction in README
4. **Action(s)**: [ sequence of actions that triggered the bug, see example below ]
  a. apply the json file into each worker node 
  b. apply the pod with dangerous-notify.json seccompProfile
5. **Error**:  pod fail to start and kubectl describe info is  
Error: failed to start container "container1": Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: listenerPath is not set: unknown

## Expected behavior

the pod can run up so I can try the command to test the notify function

## Additional information

I google the err but it seems there are few issue about this, so I want to know if we have a slack to contact with each other more than this github issue page~

**Comment by brness** [comment]
Oh it seems my libseccomp version is 2.5.1

**Comment by brness** [comment]
It's not because of the libseccomp version problem, I update it into 2.5.3, and the same error still exist!

**Comment by rata** [comment]
You can run `strings $(which dockerd) | grep listenerPath` also. If the output is empty, it means your docker version doesn't include the linked patch and therefore will remove the listenerPath field when creating the container. That is probably why you see the error.

**Comment by rata** [comment]
It would be great if you want to open a PR to clarify this in the docs, though. (that we need containerd for this, I think CRIO might work also -not sure-, and mention that docker won't work.

**Comment by brness** [comment]
Thx for all your help @rata , Sorry for the late reply. After I change the container runtime, the demo runs successfully. #27 Please informs me if there is anything needs to change and I'd loved to

**Comment by rata** [comment]
Thanks!
